name: aoc2022
description: Advent of Code 2022.
version: 1.0.0
# homepage: https://adventofcode.com/2022

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  collection: ^1.17.0
  tuple: ^2.0.1
